### ISSUE TITLE
Docker image ETS WFS 1.0 throws ClassNotFoundException

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine-docker#10]
Testing the WFS 1.0.0 RI  [1] with the teamengine-ets-wfs10 Docker image results in a ClassNotFoundException. The session details can not be opened.

Created and started Docker image with:
```
$ mvn clean package docker:build
$ docker run -p 8081:8080 --name teamengine-ets-wfs10 --rm opengis/teamengine-ets-wfs10
```

Stacktrace from the log:
```
Jul 12, 2017 9:32:14 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/teamengine] threw exception [javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found] with root cause
java.lang.ClassNotFoundException: org/apache/xerces/jaxp/DocumentBuilderFactoryImpl
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at org.apache.jasper.xmlparser.ParserUtils.parseXMLDocument(ParserUtils.java:115)
	at org.apache.jasper.xmlparser.ParserUtils.parseXMLDocument(ParserUtils.java:181)
	at org.apache.jasper.compiler.TagLibraryInfoImpl.parseTLD(TagLibraryInfoImpl.java:231)
	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:182)
	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:419)
	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:484)
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1421)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:136)
	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:329)
	at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:366)
	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:476)
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1421)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2536)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2525)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs100?service=WFS&request=GetCapabilities

**Comment by keshavnangare** [comment]
@lgoltz 

I am able to reproduce this issue with the docker environment. I think the issue is with the Tomcat 7 which is using in docker and if we execute the same test in the Tomcat 8 it worked.

I have tested this same test with `Tomcat 8.0.20` and able to view the test result.

I will try with another revision of tomcat & will let you know.

**Comment by dstenger** [comment]
Is replaced by https://github.com/opengeospatial/ets-wfs10/issues/19.
